version: "3.9"
# compose file for nginx
services:
  nginx_main:
    build:
      context: ./proxyng
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
  weba:
    image: nginx
    volumes:
      - ./weba/html:/usr/share/nginx/html
    restart: always
    ports:
      - "8081:80"
  webb:
    image: nginx
    volumes:
      - ./webb/html:/usr/share/nginx/html
    restart: always
    ports:
      - "8082:80"
  webc:
    image: nginx
    volumes:
      - ./webc/html:/usr/share/nginx/html
    restart: always
    ports:
      - "8083:80"

