version: "3.9"

services:
  nginx_main:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - my-nfs-volume:/nfs
      # - my-cifs-volume:/cifs

volumes:
  my-nfs-volume:
   name: my-nfs-volume
   driver_opts:
      type: "nfs"
      o: "addr=10.11.12.13,nolock,rw,soft"
      device: ":/folder/on/NFS/device"
  # my-cifs-volume:
  #   driver_opts:
  #     type: "cifs"
  #     o: "username=supercool,password=noboDyCanGue55,uid=1000,gid=1000,file_mode=0777,dir_mode=0777,noexec,nosuid,nosetuids,nodev,vers=1.0"
  #     device: "//10.11.12.14/folder/on/CIFS/device/"